--멤버--
DROP TABLE MEMBER;
DROP TABLE STUDENT;
DROP TABLE TEACHER;
DROP TABLE LESSON;
DROP TABLE LESSON_ENROLL;
DROP TABLE MATCHING;
DROP TABLE ID_PICTURE;
DROP TABLE ID_CARD;a
DROP TABLE REPORT_CARD;
DROP TABLE DISTRICTS;
DROP TABLE TALARM;
DROP TABLE LESSON_REVIEW;
--1대1문의--
DROP TABLE QNA_QUESTION;
DROP TABLE QNA_TYPE;
DROP TABLE QNA_ANSWER;
DROP TABLE QNA_FILE;
--채팅--
DROP TABLE ROOM;
--문제풀이--
DROP TABLE SOLUTION;
DROP TABLE SOLUTION_CMT;
DROP TABLE SOLUTION_FILES;
DROP TABLE SOLUTION_CMT_FILES;
DROP TABLE SOLUTION_HEART;
DROP TABLE POLICE;
DROP TABLE POLICE_CMT;
--자유게시판--
DROP TABLE BOARD;
DROP TABLE BOARD_CATEGORY;
DROP TABLE BOARD_LIKE;
DROP TABLE BOARD_REPORT;
DROP TABLE BOARD_REPLY;
DROP TABLE REPLY_REPORT;
--멤버--
DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_RCNO;
DROP SEQUENCE SEQ_MANO;
DROP SEQUENCE SEQ_LENO;
DROP SEQUENCE SEQ_ICNO;
DROP SEQUENCE SEQ_IPNO;
DROP SEQUENCE SEQ_LNO;
DROP SEQUENCE SEQ_DNO;
DROP SEQUENCE TA_NO;
DROP SEQUENCE SEQ_RENO;
--1대1문의--
DROP SEQUENCE SEQ_QNO;
DROP SEQUENCE SEQ_QFNO;
--채팅--

DROP SEQUENCE SEQ_RONO;
--문제풀이--
DROP SEQUENCE SEQ_SNO;
DROP SEQUENCE SEQ_SCNO;
DROP SEQUENCE SEQ_SHNO;
DROP SEQUENCE SEQ_SFNO;
DROP SEQUENCE SEQ_SCFNO;
DROP SEQUENCE SEQ_PNO;
DROP SEQUENCE SEQ_PCNO;

--자유게시판--
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_BLNO;
DROP SEQUENCE SEQ_BRNO;
DROP SEQUENCE SEQ_RNO;
DROP SEQUENCE SEQ_RRNO;


------------------------------------------------회원정보-------------------------------------------------
CREATE TABLE MEMBER(
 USER_NO NUMBER PRIMARY KEY,
 STUDENT VARCHAR2(1) CHECK (STUDENT IN('Y','N')),
 TEACHER VARCHAR2(1) CHECK (TEACHER IN('Y','N')),
 USER_ID VARCHAR2(30) NOT NULL,
 USER_PWD VARCHAR2(100) NOT NULL,
 USER_NAME VARCHAR2(30) NOT NULL,
 GENDER VARCHAR2(1) CHECK (GENDER IN('M','F')) ,
 EMAIL VARCHAR2(100) NOT NULL,
 BIRTH DATE NOT NULL,
 ENROLL_DATE DATE DEFAULT SYSDATE,
 MODIFY_DATE DATE DEFAULT SYSDATE,
 APPROVAL VARCHAR2(1)  DEFAULT 'N' CHECK (APPROVAL IN('Y','N','D')),
 STATUS VARCHAR2(1) CHECK (STATUS IN('Y','N'))
 );
 
 COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
 COMMENT ON COLUMN MEMBER.STUDENT IS '학생';
 COMMENT ON COLUMN MEMBER.TEACHER IS '선생';
 COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
 COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
 COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
 COMMENT ON COLUMN MEMBER.GENDER IS '성별';
 COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
 COMMENT ON COLUMN MEMBER.BIRTH IS '생년월일';
 COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
 COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '회원정보 수정일';
 COMMENT ON COLUMN MEMBER.APPROVAL IS '회원 승인 여부';
 COMMENT ON COLUMN MEMBER.STATUS IS '회원상태';
 
 CREATE SEQUENCE SEQ_MNO NOCACHE;
 
 
 INSERT INTO MEMBER
VALUES (SEQ_MNO.NEXTVAL,'N','N', 'admin', '1234', 'admin','M', 'admin', '20220202',DEFAULT, DEFAULT,'Y','Y');


------------------------------------------------회원정보(학생)-------------------------------------------------
CREATE TABLE STUDENT(
USER_NO NUMBER PRIMARY KEY,
YEAR NUMBER NOT NULL,
KO NUMBER NOT NULL,
MATH NUMBER NOT NULL,
ENG NUMBER NOT NULL
);

COMMENT ON COLUMN STUDENT.USER_NO IS '회원번호';
COMMENT ON COLUMN STUDENT.YEAR IS '학년';
COMMENT ON COLUMN STUDENT.KO IS '언어성적';
COMMENT ON COLUMN STUDENT.MATH IS '수학성적';
COMMENT ON COLUMN STUDENT.ENG IS '영어성적';

------------------------------------------------회원정보(선생)-------------------------------------------------
CREATE TABLE TEACHER(
USER_NO NUMBER PRIMARY KEY,
SELF_INTRODUCTION VARCHAR2(4000) NOT NULL,
SCHOOL_INFO VARCHAR2(100) NOT NULL,
RATING NUMBER DEFAULT 1
);

COMMENT ON COLUMN TEACHER.USER_NO IS '회원번호';
COMMENT ON COLUMN TEACHER.SELF_INTRODUCTION IS '자기소개';
COMMENT ON COLUMN TEACHER.SCHOOL_INFO IS '학교정보';
COMMENT ON COLUMN TEACHER.RATING IS '선생님등급';

------------------------------------------------첨부파일(성적표)-------------------------------------------------
CREATE TABLE REPORT_CARD(
RC_NO NUMBER PRIMARY KEY,
RC_ORIGINNAME VARCHAR2(100) NOT NULL,
RC_SYSNAME VARCHAR2(100) NOT NULL,
STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N')),
USER_NO NUMBER NOT NULL
);

COMMENT ON COLUMN REPORT_CARD.RC_NO IS '성적표 첨부파일 번호';
COMMENT ON COLUMN REPORT_CARD.RC_ORIGINNAME IS '원본명';
COMMENT ON COLUMN REPORT_CARD.RC_SYSNAME IS '수정명';
COMMENT ON COLUMN REPORT_CARD.STATUS IS '첨부파일 상태';
COMMENT ON COLUMN REPORT_CARD.USER_NO IS '회원번호';

 CREATE SEQUENCE SEQ_RCNO NOCACHE;
 
 ------------------------------------------------수업등록(선생님)-------------------------------------------------
 CREATE TABLE LESSON_ENROLL(
 LE_NO NUMBER PRIMARY KEY,
 USER_NO NUMBER NOT NULL,
 SUBJECT VARCHAR2(30) NOT NULL,
 FEE NUMBER NOT NULL,
 LE_STYLE VARCHAR2(4000) NOT NULL,
 T_YEAR NUMBER NOT NULL,
 AREA VARCHAR2(4000) NOT NULL,
 CAREER VARCHAR2(100) NOT NULL,
 LE_DAY VARCHAR2(100) NOT NULL,
 TEACHINGSTYLE VARCHAR2(30) NOT NULL,
 LE_ORIGINNAME VARCHAR2(4000) NOT NULL,
 LE_CHANGENAME VARCHAR2(4000) NOT NULL,
 STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N'))
 );


 COMMENT ON COLUMN LESSON_ENROLL.LE_NO IS '수업등록번호';
 COMMENT ON COLUMN LESSON_ENROLL.USER_NO IS '유저번호';
 COMMENT ON COLUMN LESSON_ENROLL.SUBJECT IS '과목';
 COMMENT ON COLUMN LESSON_ENROLL.FEE IS '과외비';
 COMMENT ON COLUMN LESSON_ENROLL.LE_STYLE IS '과외스타일';
 COMMENT ON COLUMN LESSON_ENROLL.T_YEAR IS '담당학년';
 COMMENT ON COLUMN LESSON_ENROLL.AREA IS '과외지역';
 COMMENT ON COLUMN LESSON_ENROLL.CAREER IS '과외경력';
 COMMENT ON COLUMN LESSON_ENROLL.LE_DAY IS '과외요일';
 COMMENT ON COLUMN LESSON_ENROLL.TEACHINGSTYLE IS '선호 수업방식';
 COMMENT ON COLUMN LESSON_ENROLL.LE_ORIGINNMAE IS '수업영상원본명';
 COMMENT ON COLUMN LESSON_ENROLL.LE_CHANGENAME IS '수업영상수정명';
 COMMENT ON COLUMN LESSON_ENROLL.STATUS IS '상태';


 CREATE SEQUENCE SEQ_LENO NOCACHE;
 
  ------------------------------------------------과외매칭(학생)-------------------------------------------------
  CREATE TABLE MATCHING(
  MA_NO NUMBER PRIMARY KEY,
  GROUP_NO NUMBER NOT NULL,
  USER_NO NUMBER NOT NULL,
  RANDOM VARCHAR2(1) NOT NULL,
  GENDER VARCHAR2(1) NOT NULL,
  SUBJECT VARCHAR2(30) NOT NULL,
  AREA VARCHAR2(30) NOT NULL,
  FEE NUMBER NOT NULL,
  PEOPLE NUMBER NOT NULL,
  CHIEF VARCHAR2(1) DEFAULT 'Y' CHECK (CHIEF IN('Y','N')),
  MA_DAY VARCHAR2(100) NOT NULL,
  ENROLLDATE DATE DEFAULT SYSDATE,
  ALERT VARCHAR2(1),
  ALERT2 VARCHAR2(1),
  URL VARCHAR(1),
  SENDURL VARCHAR2 (1),
  URL_ALERT VARCHAR2(1),
  STATUS VARCHAR2(1) 
  );
  
  
  
 
       
 
   COMMENT ON COLUMN MATCHING.MA_NO IS '매칭번호';
   COMMENT ON COLUMN MATCHING.GROUP_NO IS '매칭그룹번호';
   COMMENT ON COLUMN MATCHING.USER_NO IS '유저번호';
   COMMENT ON COLUMN MATCHING.RANDOM IS '랜덤유무';
   COMMENT ON COLUMN MATCHING.GENDER IS '성별';
   COMMENT ON COLUMN MATCHING.SUBJECT IS '과목';
   COMMENT ON COLUMN MATCHING.AREA IS '과외지역';
   COMMENT ON COLUMN MATCHING.FEE IS '과외비';
   COMMENT ON COLUMN MATCHING.PEOPLE IS '매칭인원';
   COMMENT ON COLUMN MATCHING.CHIEF IS '방장';
   COMMENT ON COLUMN MATCHING.ENROLLDATE IS '매칭등록일';
   COMMENT ON COLUMN MATCHING.MA_DAY IS '과외요일';
   COMMENT ON COLUMN MATCHING.ALERT IS '알람YN';
   COMMENT ON COLUMN MATCHING.ALERT IS '알람YN2';
   COMMENT ON COLUMN MATCHING.URL IS 'URL등록유무';
   COMMENT ON COLUMN MATCHING.STATUS IS '매칭상태';
 
  
   CREATE SEQUENCE SEQ_MANO NOCACHE;
    
    
   ------------------------------------------------과외정보(선생,학생)-------------------------------------------------
   
   CREATE TABLE LESSON(
   L_NO NUMBER PRIMARY KEY,
   STUDENT_NO NUMBER NOT NULL,
   TEACHER_NO NUMBER NOT NULL,
   SUBJECT VARCHAR2(30) NOT NULL,
   START_DATE DATE DEFAULT SYSDATE,
   END_DATE DATE ,
   STATUS VARCHAR2(1) NOT NULL
   );
   
   COMMENT ON COLUMN LESSON.L_NO IS '과외번호';
   COMMENT ON COLUMN LESSON.STUDENT_NO IS '학생번호';
   COMMENT ON COLUMN LESSON.TEACHER_NO IS '선생번호';
   COMMENT ON COLUMN LESSON.SUBJECT IS '과목';
   COMMENT ON COLUMN LESSON.START_DATE IS '과외시작일';
   COMMENT ON COLUMN LESSON.END_DATE IS '과외종료일';
   COMMENT ON COLUMN LESSON.STATUS IS '상태';
   
   CREATE SEQUENCE SEQ_LNO NOCACHE;
   
      ------------------------------------------------첨부파일(재학증명서)-------------------------------------------------
     CREATE TABLE ID_CARD(
    IC_NO NUMBER PRIMARY KEY,
    IC_ORIGINNAME VARCHAR2(100) NOT NULL,
    IC_SYSNAME VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N')),
    USER_NO NUMBER NOT NULL
    );

    COMMENT ON COLUMN ID_CARD.IC_NO IS '재학증명서 첨부파일 번호';
    COMMENT ON COLUMN ID_CARD.IC_ORIGINNAME IS '원본명';
    COMMENT ON COLUMN ID_CARD.IC_SYSNAME IS '수정명';
    COMMENT ON COLUMN ID_CARD.STATUS IS '첨부파일 상태';
    COMMENT ON COLUMN ID_CARD.USER_NO IS '회원번호';

    CREATE SEQUENCE SEQ_ICNO NOCACHE;
      
      ------------------------------------------------첨부파일(증명사진)-------------------------------------------------
        CREATE TABLE ID_PICTURE(
    IP_NO NUMBER PRIMARY KEY,
    IP_ORIGINNAME VARCHAR2(100) NOT NULL,
    IP_SYSNAME VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y','N')),
    USER_NO NUMBER NOT NULL
    );

    COMMENT ON COLUMN ID_PICTURE.IP_NO IS '증명사진 첨부파일 번호';
    COMMENT ON COLUMN ID_PICTURE.IP_ORIGINNAME IS '원본명';
    COMMENT ON COLUMN ID_PICTURE.IP_SYSNAME IS '수정명';
    COMMENT ON COLUMN ID_PICTURE.STATUS IS '첨부파일 상태';
    COMMENT ON COLUMN ID_PICTURE.USER_NO IS '회원번호';

    CREATE SEQUENCE SEQ_IPNO NOCACHE;
    
    ------------------------------------------------1대1문의-------------------------------------------------
    CREATE TABLE QNA_QUESTION(
    QNA_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    TYPE_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    QUESTION_CONTENT VARCHAR2(4000) NOT NULL,
    QUESTION_DATE DATE DEFAULT SYSDATE,
    QUESTION_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (QUESTION_STATUS IN('Y','N'))
    );
        
     COMMENT ON COLUMN QNA_QUESTION.QNA_NO IS '1대1문의번호';
     COMMENT ON COLUMN QNA_QUESTION.USER_NO IS '작성자 번호';
     COMMENT ON COLUMN QNA_QUESTION.TYPE_NO IS '유형번호';
     COMMENT ON COLUMN QNA_QUESTION.TITLE IS '제목';
     COMMENT ON COLUMN QNA_QUESTION.QUESTION_CONTENT IS '내용';
     COMMENT ON COLUMN QNA_QUESTION.QUESTION_DATE IS '작성일';
     COMMENT ON COLUMN QNA_QUESTION.QUESTION_STATUS IS '문의상태';
     
    CREATE SEQUENCE SEQ_QNO NOCACHE;
    
    ------------------------------------------------1대1문의 유형-------------------------------------------------
    CREATE TABLE QNA_TYPE(
    TYPE_NO NUMBER PRIMARY KEY,
    TYPE_NAME VARCHAR2(100) NOT NULL
    );
    
    COMMENT ON COLUMN QNA_TYPE.TYPE_NO IS '문의유형번호';
    COMMENT ON COLUMN QNA_TYPE.TYPE_NAME IS '문의유형';
   
    INSERT INTO QNA_TYPE VALUES (1,'이용문의');
    INSERT INTO QNA_TYPE VALUES (2,'회원정보문의');
    INSERT INTO QNA_TYPE VALUES (3,'기타');
    
    ------------------------------------------------1대1문의 답변-------------------------------------------------
    
    CREATE  TABLE QNA_ANSWER(
    QNA_NO NUMBER NOT NULL,
    ANSWER_CONTENT VARCHAR2(4000) NOT NULL,
    ANSWER_DATE DATE DEFAULT SYSDATE,
    ANSWER_STATUS VARCHAR2(1) NOT NULL
    );
    COMMENT ON COLUMN QNA_ANSWER.QNA_NO IS '1대1문의번호';
    COMMENT ON COLUMN QNA_ANSWER.ANSWER_CONTENT IS '답변내용';
    COMMENT ON COLUMN QNA_ANSWER.ANSWER_DATE IS '답변등록일';
    COMMENT ON COLUMN QNA_ANSWER.ANSWER_STATUS IS '답변상태';
    
    ------------------------------------------------1대1문의 첨부파일-------------------------------------------------
    
    CREATE TABLE QNA_FILE(
    QF_NO NUMBER PRIMARY KEY,
    QNA_NO NUMBER NOT NULL,
    QF_ORIGINNAME VARCHAR2(100) NOT NULL,
    QF_SYSNAME VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
    );
    
    COMMENT ON COLUMN QNA_FILE.QF_NO IS '1대1문의첨부파일번호';
    COMMENT ON COLUMN QNA_FILE.QNA_NO IS '참조 1대1문의번호';
    COMMENT ON COLUMN QNA_FILE.QF_ORIGINNAME IS '파일 원본명';
    COMMENT ON COLUMN QNA_FILE.QF_SYSNAME IS '파일 수정명';
    COMMENT ON COLUMN QNA_FILE.STATUS IS '첨부파일 상태';
    
    CREATE SEQUENCE SEQ_QFNO NOCACHE;
    
    ------------------------------------------------문제풀이게시판-------------------------------------------------
    
    CREATE TABLE SOLUTION(
    SOLUTION_NO NUMBER PRIMARY KEY,
    SUBJECT VARCHAR2(10) NOT NULL,
    TAG VARCHAR2(100) NOT NULL,
    USER_NO NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    SOLUTION_CONTENTS VARCHAR2(4000) NOT NULL,
    COUNT NUMBER	DEFAULT 0 NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y'  CHECK (STATUS IN('Y', 'N'))  NOT NULL
    );
    
    COMMENT ON COLUMN SOLUTION.SOLUTION_NO IS   '문제풀이 게시글 번호';
    COMMENT ON COLUMN SOLUTION.SUBJECT IS   '문제풀이 게시글 과목';
    COMMENT ON COLUMN SOLUTION.TAG IS   '해쉬태그';
    COMMENT ON COLUMN SOLUTION.USER_NO IS '작성 회원 번호';
    COMMENT ON COLUMN SOLUTION.TITLE IS    '문제풀이 게시글 제목';
    COMMENT ON COLUMN SOLUTION.SOLUTION_CONTENTS IS '문제풀이 게시글 내용';
    COMMENT ON COLUMN SOLUTION.COUNT IS   '문제풀이 게시글 조회수';
    COMMENT ON COLUMN SOLUTION.CREATE_DATE IS   '문제풀이 게시글 작성일';
    COMMENT ON COLUMN SOLUTION.STATUS IS    '문제풀이 게시글 상태';
    
    CREATE SEQUENCE SEQ_SNO;
    
    ------------------------------------------------문제풀이게시판첨부파일-------------------------------------------------
    
    CREATE TABLE SOLUTION_FILES(
    SF_NO NUMBER PRIMARY KEY,
    SF_ORIGINNAME VARCHAR2(4000) NOT NULL,
    SF_SYSNAME VARCHAR2(4000) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
    SOLUTION_NO NUMBER NOT NULL
    );

    COMMENT ON COLUMN SOLUTION_FILES.SF_NO IS '문제풀이 게시글 첨부파일 번호';
    COMMENT ON COLUMN SOLUTION_FILES.SF_ORIGINNAME IS '사용자가 보는 첨부파일 이름';
    COMMENT ON COLUMN SOLUTION_FILES.SF_SYSNAME IS '시스템에 저장된 첨부파일 이름';
    COMMENT ON COLUMN SOLUTION_FILES.STATUS IS '첨부파일 상태';
    COMMENT ON COLUMN SOLUTION_FILES.SOLUTION_NO IS '원본 게시글 번호';
    
    CREATE SEQUENCE SEQ_SFNO;
    
    ------------------------------------------------문제풀이게시판신고-------------------------------------------------
    CREATE TABLE POLICE(
    P_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    REASON VARCHAR2(100) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    SOLUTION_NO NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN POLICE.P_NO IS '게시판 신고 번호';
    COMMENT ON COLUMN POLICE.USER_NO IS '신고한 회원 번호';
    COMMENT ON COLUMN POLICE.REASON IS '신고 유형';
    COMMENT ON COLUMN POLICE.CREATE_DATE IS '신고 등록일';
    COMMENT ON COLUMN POLICE.SOLUTION_NO IS '신고된 게시물 번호';
    
    CREATE SEQUENCE SEQ_PNO;
    
    ------------------------------------------------문제풀이게시판좋아요-------------------------------------------------
    CREATE TABLE SOLUTION_HEART(
    SH_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    SOLUTION_NO NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN SOLUTION_HEART.SH_NO IS '추천 번호';
    COMMENT ON COLUMN SOLUTION_HEART.USER_NO IS '추천 누른 사람 번호';
    COMMENT ON COLUMN SOLUTION_HEART.SOLUTION_NO IS '추천한 게시물 NO';
    
    CREATE SEQUENCE SEQ_SHNO;
    
    ------------------------------------------------문제풀이게시판댓글-------------------------------------------------
    
    CREATE TABLE SOLUTION_CMT(
    SC_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    SOLUTION_CMT_CONTENTS VARCHAR2(400) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
    SOLUTION_NO NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN SOLUTION_CMT.SC_NO IS '문제풀이 댓글 번호';
    COMMENT ON COLUMN SOLUTION_CMT.USER_NO IS '작성 회원 번호';
    COMMENT ON COLUMN SOLUTION_CMT.SOLUTION_CMT_CONTENTS IS '댓글 내용';
    COMMENT ON COLUMN SOLUTION_CMT.CREATE_DATE IS '댓글 등록일';
    COMMENT ON COLUMN SOLUTION_CMT.STATUS IS '댓글 상태';
    COMMENT ON COLUMN SOLUTION_CMT.SOLUTION_NO IS '원본 게시물 번호';
    
    CREATE SEQUENCE SEQ_SCNO;
    
    ------------------------------------------------문제풀이게시판댓글첨부파일-------------------------------------------------
    CREATE TABLE SOLUTION_CMT_FILES(
    SCF_NO NUMBER PRIMARY KEY,
    SCF_ORIGINNAME VARCHAR2(4000) NOT NULL,
    SCF_SYSNAME VARCHAR2(4000) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL,
    SC_NO NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN SOLUTION_CMT_FILES.SCF_NO IS '문제풀이 댓글 첨부파일 번호';
    COMMENT ON COLUMN SOLUTION_CMT_FILES.SCF_ORIGINNAME IS '사용자가 보는 첨부파일 이름';
    COMMENT ON COLUMN SOLUTION_CMT_FILES.SCF_SYSNAME IS '시스템에 저장된 첨부파일 이름';
    COMMENT ON COLUMN SOLUTION_CMT_FILES.STATUS IS '첨부파일 상태';
    COMMENT ON COLUMN SOLUTION_CMT_FILES.SC_NO IS '원본 댓글 번호';

    CREATE SEQUENCE SEQ_SCFNO;
    ------------------------------------------------문제풀이게시판댓글신고-------------------------------------------------
    CREATE TABLE POLICE_CMT(
    PC_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    REASON VARCHAR2(100) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    SC_NO NUMBER NOT NULL
    );

    COMMENT ON COLUMN POLICE_CMT.PC_NO IS '댓글 신고 번호';
    COMMENT ON COLUMN POLICE_CMT.USER_NO IS '신고한 회원 번호';
    COMMENT ON COLUMN POLICE_CMT.REASON IS '신고 유형';
    COMMENT ON COLUMN POLICE_CMT.CREATE_DATE IS '신고 등록일';
    COMMENT ON COLUMN POLICE_CMT.SC_NO IS '신고된 댓글 번호';
    
    CREATE SEQUENCE SEQ_PCNO;
    
    ------------------------------------------------자유게시판-------------------------------------------------
    CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    CATEGORY_NO NUMBER NOT NULL,
    TITLE VARCHAR2(4000) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    COUNT NUMBER DEFAULT 0 NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N'))
    BF_SYSNAME VARCHAR2(100),
    BF_ORIGINNAME VARCHAR2(100)
    
    );
    
    COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
    COMMENT ON COLUMN BOARD.USER_ID IS '작성자 아이디';
    COMMENT ON COLUMN BOARD.CATEGORY_NO IS '카테고리 번호';
    COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
    COMMENT ON COLUMN BOARD.CONTENT IS '게시글 내용';
    COMMENT ON COLUMN BOARD.COUNT IS '조회수';
    COMMENT ON COLUMN BOARD.ENROLL_DATE IS '작성일';
    COMMENT ON COLUMN BOARD.STATUS IS '게시글 상태';
    COMMENT ON COLUMN BOARD.BF_SYSNAME IS '저장된 파일명';
    COMMENT ON COLUMN BOARD.BF_ORIGINNAME IS '원본 파일명';
    
    CREATE SEQUENCE SEQ_BNO;
    ------------------------------------------------자유게시판 카테고리-------------------------------------------------
    CREATE TABLE BOARD_CATEGORY(
        CATEGORY_NO NUMBER PRIMARY KEY,
        CATEGORY_NAME VARCHAR2(100) NOT NULL
    );
    COMMENT ON COLUMN BOARD_CATEGORY.CATEGORY_NO IS '카테고리 번호';
    COMMENT ON COLUMN BOARD_CATEGORY.CATEGORY_NAME IS '카테고리 이름';
    
    --학생--
    INSERT INTO BOARD_CATEGORY VALUES(1,'문제집공유');
    INSERT INTO BOARD_CATEGORY VALUES(2,'스터디모집');
    INSERT INTO BOARD_CATEGORY VALUES(3,'기타');
    --선생--
    INSERT INTO BOARD_CATEGORY VALUES(51,'답안지 공유');
    INSERT INTO BOARD_CATEGORY VALUES(52,'과외정보');
    INSERT INTO BOARD_CATEGORY VALUES(53,'기타');
    
    ------------------------------------------------자유게시판 신고-------------------------------------------------
    CREATE TABLE BOARD_REPORT(
    BR_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    REPORT_DATE DATE DEFAULT SYSDATE,
    REASON VARCHAR2(100) NOT NULL
    );
    
    COMMENT ON COLUMN BOARD_REPORT.BR_NO IS '게시글 신고번호';
    COMMENT ON COLUMN BOARD_REPORT.BOARD_NO IS '참조게시글번호';
    COMMENT ON COLUMN BOARD_REPORT.USER_NO IS '신고한 유저';
    COMMENT ON COLUMN BOARD_REPORT.REPORT_DATE IS '신고일';
    COMMENT ON COLUMN BOARD_REPORT.REASON IS '신고사유';
    
    
    CREATE SEQUENCE SEQ_BRNO;
    ------------------------------------------------자유게시판 좋아요 -------------------------------------------------
    CREATE TABLE BOARD_LIKE(
        BL_NO NUMBER PRIMARY KEY,
        BOARD_NO NUMBER NOT NULL,
        USER_NO NUMBER NOT NULL
    );
    
    COMMENT ON COLUMN BOARD_LIKE.BL_NO IS '좋아요 번호';
    COMMENT ON COLUMN BOARD_LIKE.BOARD_NO IS '참조게시물 번호';
    COMMENT ON COLUMN BOARD_LIKE.USER_NO IS '좋아요 누른 유저';
    
    CREATE SEQUENCE SEQ_BLNO;
    ------------------------------------------------자유게시판 댓글 -------------------------------------------------
    CREATE TABLE BOARD_REPLY(
        R_NO NUMBER NOT NULL,
        BOARD_NO NUMBER NOT NULL,
        USER_NO NUMBER NOT NULL,
        CONTENT VARCHAR2(4000) NOT NULL,
        BR_DATE DATE DEFAULT SYSDATE,
        STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) NOT NULL
    );
    
     COMMENT ON COLUMN BOARD_REPLY.R_NO IS '댓글번호';
     COMMENT ON COLUMN BOARD_REPLY.BOARD_NO IS '참조댓글번호';
     COMMENT ON COLUMN BOARD_REPLY.USER_NO IS '유저번호';
     COMMENT ON COLUMN BOARD_REPLY.CONTENT IS '댓글내용';
     COMMENT ON COLUMN BOARD_REPLY.BR_DATE IS '댓글작성일';
     COMMENT ON COLUMN BOARD_REPLY.STATUS IS '댓글 상태';
     
      CREATE SEQUENCE SEQ_RNO;
   
    ------------------------------------------------자유게시판 댓글 신고-------------------------------------------------
    CREATE TABLE REPLY_REPORT(
    RR_NO NUMBER PRIMARY KEY,
    REPLY_NO NUMBER NOT NULL,
    USER_NO NUMBER NOT NULL,
    REPORT_DATE DATE DEFAULT SYSDATE,
    REASON VARCHAR2(4000) NOT NULL
    );
    
    COMMENT ON COLUMN REPLY_REPORT.RR_NO IS '게시글 신고번호';
    COMMENT ON COLUMN REPLY_REPORT.REPLY_NO IS '참조게시글번호';
    COMMENT ON COLUMN REPLY_REPORT.USER_NO IS '신고한 유저';
    COMMENT ON COLUMN REPLY_REPORT.REPORT_DATE IS '신고일';
    COMMENT ON COLUMN REPLY_REPORT.REASON IS '신고사유';
    
    CREATE SEQUENCE SEQ_RRNO;
    
    ------------------------------------------------지역명 테이블-------------------------------------------------    
    CREATE TABLE DISTRICTS(
    D_NO NUMBER PRIMARY KEY,
    AREA VARCHAR2(100) NOT NULL
    );
    
    COMMENT ON COLUMN DISTRICTS.D_NO IS '지역명테이블 PK';
    COMMENT ON COLUMN DISTRICTS.AREA IS '지역명';
    
    CREATE SEQUENCE SEQ_DNO;
    
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'종로구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'중구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'용산구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'성동구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'광진구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'동대문구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'중랑구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'성북구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'강북구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'도봉구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'노원구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'은평구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'서대문구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'마포구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'양천구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'강서구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'구로구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'금천구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'영등포구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'동작구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'관악구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'서초구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'강남구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'송파구');
    INSERT INTO DISTRICTS VALUES(SEQ_DNO.NEXTVAL,'강동구');
    
    COMMIT;
    
    


-------------------채팅방--------------------------


CREATE TABLE ROOM (
    RONO NUMBER PRIMARY KEY,
    ROOM_NO NUMBER NOT NULL,
    ROOM_URL VARCHAR2(100) NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y'
);
CREATE SEQUENCE SEQ_RONO NOCACHE;
COMMENT ON COLUMN ROOM.RONO IS '채팅방 순서';
COMMENT ON COLUMN ROOM.ROOM_NO IS '채팅방 번호';
COMMENT ON COLUMN ROOM.ROOM_URL IS '채팅방 링크';
COMMENT ON COLUMN ROOM.STATUS IS '채팅방 상태';



COMMIT;

------------------------선생님 알람테이블-------------------
CREATE TABLE TALARM(
    TA_NO NUMBER PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    GROUP_NO NUMBER NOT NULL,
    ALERT VARCHAR2(1) NOT NULL,
    ALARM VARCHAR2(1) NOT NULL,
    ENROLL_DATE DATE NOT NULL,
    STATUS VARCHAR2(1) NOT NULL
    );
CREATE SEQUENCE SEQ_TANO NOCACHE;
COMMENT ON COLUMN TALARM.TA_NO IS '알람테이블 PK';
COMMENT ON COLUMN TALARM.USER_NO IS '선생님NO';
COMMENT ON COLUMN TALARM.GROUP_NO IS '채팅방초대한그룹NO';
COMMENT ON COLUMN TALARM.ALERT IS 'ALERTY/N';
COMMENT ON COLUMN TALARM.ALARM IS 'ALARMY/N';

------------------ 선생님 후기 테이블 -------------------------------

CREATE TABLE LESSON_REVIEW (
    RENO NUMBER PRIMARY KEY,
    REF_LENO NUMBER NOT NULL,
    RE_UNO NUMBER NOT NULL,
    RE_UNAME VARCHAR2(30) NOT NULL,
    RE_TEXT VARCHAR2(2000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y'
);
CREATE SEQUENCE SEQ_RENO NOCACHE;

COMMENT ON COLUMN LESSON_REVIEW.RENO IS '후기 번호';
COMMENT ON COLUMN LESSON_REVIEW.REF_LENO IS '참조 과외번호';
COMMENT ON COLUMN LESSON_REVIEW.RE_UNO IS '회원 번호';
COMMENT ON COLUMN LESSON_REVIEW.RE_UNAME IS '회원 이름';
COMMENT ON COLUMN LESSON_REVIEW.RE_TEXT IS '후기 내용';
COMMENT ON COLUMN LESSON_REVIEW.CREATE_DATE IS '후기 작성일';
COMMENT ON COLUMN LESSON_REVIEW.STATUS IS '후기 상태';

COMMIT;